# Generated by Django 4.1.7 on 2023-05-19 20:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('won', 'Won'), ('lost', 'Lost')], default='new', max_length=10)),
                ('converted_to_client', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('address_1', models.CharField(default='Niet Bekend', max_length=255)),
                ('address_2', models.CharField(default='Niet Bekend', max_length=255)),
                ('address_3', models.CharField(default='Niet Bekend', max_length=255)),
                ('telefoon_nummer', models.PositiveSmallIntegerField(default=0)),
                ('woon_plaats', models.CharField(default='Woonplaats', max_length=255)),
                ('vak_gebied', models.CharField(default='Vak Gebied', max_length=255)),
                ('lead_datum', models.DateField(verbose_name=datetime.date(1111, 11, 1))),
                ('kvk', models.PositiveSmallIntegerField(default=0)),
                ('belasting_nummer', models.CharField(default='Niet Bekend', max_length=255)),
                ('firma_type', models.CharField(choices=[('zzp', 'Zzp'), ('bv', 'Bv'), ('vog', 'Vof'), ('stichting', 'Stichting')], default='zzp', max_length=10)),
                ('contact_persoon', models.CharField(default='Contact Persoon', max_length=255)),
                ('contact_persoon_email', models.EmailField(default='EmailHierInvullen@snel.nl', max_length=254)),
                ('contact_datum_1', models.DateField(verbose_name=datetime.date(1111, 11, 1))),
                ('contact_datum_2', models.DateField(verbose_name=datetime.date(1111, 11, 1))),
                ('contact_datum_3', models.DateField(verbose_name=datetime.date(1111, 11, 1))),
                ('opmerkingen', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
