# Generated by Django 4.1.7 on 2023-05-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='pakket',
            field=models.CharField(choices=[('basic', 'Basic'), ('zilver', 'Zilver'), ('goud', 'Goud')], default='basic', max_length=10),
        ),
        migrations.AlterField(
            model_name='lead',
            name='contact_datum_1',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='lead',
            name='contact_datum_2',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='lead',
            name='contact_datum_3',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_datum',
            field=models.DateField(),
        ),
    ]
